set -g prefix C-x
unbind-key C-b

set -g mode-keys vi
set -g status-position bottom
set -g base-index 1
set -g pane-base-index 1
set -g renumber-window on
set -g history-limit 10000
setw -g mouse on

bind j next-window 
bind k previous-window
